### ISSUE TITLE
add support for *Exclude

### ISSUE THREAD

**Issue by rjchallis** [genomehubs/goat-cli#11]

**Comment by Euphrasiologist** [comment]
I can't remember what this was in reference to, can you remind me please @rjchallis ?

**Comment by rjchallis** [comment]
The table of results includes rows where any one of the fields has a direct value (or descendant value). Some of the values returned may be missing or based on ancestral estimates. I know goat-cli aims to keep things simple so you may not wish to support options such as `excludeAnscestral`, but it would provide a way to filter the results table when returning multiple columns to ensure that values for an attribute were not based on ancestral estimates. E.g. when returning `genome_size` and `assembly_span` if a user is most concerned with the C value-based genome size estimates for various families then it may be useful to have the option to guarantee that these are derived from descendant values with any available assembly span shown alongside.

**Comment by Euphrasiologist** [comment]
I'm investigating this again. I'm just interested in the URL construction here. Say I have two variables, `assembly_span` and `c_value`. Is this the way to get only direct values for both?:

```
&excludeAncestral%5B0%5D=assembly_span
&excludeAncestral%5B1%5D=c_value
&excludeDescendant%5B0%5D=assembly_span
&excludeDescendant%5B1%5D=c_value
&excludeMissing%5B0%5D=assembly_span
&excludeMissing%5B1%5D=c_value
```

Essentially turning off all the switches except the direct ('green') ones?

**Comment by rjchallis** [comment]
Yes, but this will also filter out any rows where only one of these attributes is directly measured - you would need to do the search independently for each field to be sure of getting all direct values for both attributes. Also for species, a descendant value really just means that the organism was identified at a lower taxonomic level so the most useful implementation is probably to toggle off just the missing and ancestral values.

**Comment by Euphrasiologist** [comment]
Okay, yes, I agree on this. I might just change the default behaviour to this, then it's unambiguous. Now I am just trying to work out how the toggles work in the URL! Are the variables always indexed alphabetically? So if I had three variables:

- assembly_span
- gene_count
- c_value

Will this be:

assembly_span[0], c_value[1], gene_count[2] ?

**Comment by rjchallis** [comment]
the index is only there to turn repeated entries with the same key into an array so the attribute name has no effect. The `excludeAncestral`, etc, suffixes run `[0]`, `[1]`, ... so you can have `excludeAncestral[0]=gene_count&excludeAncestral[1]=assembly_span` regardless of attribute name ordering
