### ISSUE TITLE
Feature request: An extra field say if the returned value is derived or not

### ISSUE THREAD

**Issue by mahesh-panchal** [genomehubs/goat-cli#24]
Hi, I'm currently using goat-cli in a workflow which pulls busco lineages, genome size, and some other fields. It would be nice to have an extra field or some kind of flag to indicate whether the genome size (and other fields) is derived or has been experimentally determined. 
Although the `-x` flag is available, this doesn't suit my needs as I would still like to have the genome size even if it's derived.

**Comment by Euphrasiologist** [comment]
@rjchallis do you have an idea of how this might be implemented?

**Comment by Euphrasiologist** [comment]
@rjchallis option 3 looking good.

Does this work for assembly index? I checked this, and it seemed maybe not?

https://goat.genomehubs.org/search?query=tax_tree%289608%5BCanidae%5D%29%20AND%20tax_rank%28species%29&result=assembly&includeEstimates=true&summaryValues=count&taxonomy=ncbi&size=25&offset=0&fields=assembly_span%2Cassembly_span%3Adirect%2Cassembly_span%3Aancestor%2Cassembly_span%3Adescendant&names=&ranks=&sortBy=none#tax_tree(9608[Canidae])%20AND%20tax_rank(species)

**Comment by rjchallis** [comment]
no, the assembly index doesn't have any aggregated values so there are no direct, descendant, etc sources
